# This workflow will build the Java project with Maven and Ant

name: Java CI

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: setup java 17 with maven cache
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Maven dependencies
      run: |
        mvn clean install dependency:copy-dependencies

#    - name: Upload zipped executable jar
#      uses: actions/upload-artifact@v2
#      with:
#        name: SpringSalad_${{ github.event.inputs.tag_name }}
#        path: ./SpringSalad_${{ github.event.inputs.tag_name }}.jar
   
    
  
    

      
