# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'version tag'
        required: true
        default: 2.2.0
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: 'false'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout Langevin project
      uses: actions/checkout@v2
      with:
        repository: cam-center/LangevinNoVis01
        path: './langevin'
    - name: Set up environment
      env:
        BUILD_VERSION: ${{ github.event.inputs.tag_name }}
        LANGEVIN_PATH: './langevin'
      run:
        echo $BUILD_VERSION > version.txt
        echo $LANGEVIN_PATH > langevin.txt
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Setup tmate session for debugging
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
    - name: Maven dependencies
      run: mvn compile
    - name: Build with Ant
      run: ant -noinput -buildfile build-new.xml
    - name: Setup tmate session for debugging
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      
