# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'version tag'
        required: true
        default: 2.2.0
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false

env:
  BUILD_VERSION: ${{ github.event.inputs.tag_name }}
  LANGEVIN_PATH: './langevin'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout Langevin project
      uses: actions/checkout@v2
      with:
        repository: cam-center/LangevinNoVis01
        path: './langevin'
    - name: Check environment variables
      run:
        echo $BUILD_VERSION >> version.txt
        echo $LANGEVIN_PATH >> langevin.txt
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Setup tmate session for debugging
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
    - name: Maven dependencies
      run: |
        cd $LANGEVIN_PATH
        mvn compile
        cd ..
        mkdir target
        mkdir target/classes
        cp -ar $LANGEVIN_PATH/target/classes/* ./target/classes
        unzip lib/monte-repack-1.0.jar -d target/classes/
        mvn compile
    - name: Build with Ant
      run: ant -noinput -buildfile build-new.xml
    - name: Upload zipped executable jar
      uses: actions/upload-artifact@v2
      with:
        name: SpringSalad_${{ github.event.inputs.tag_name }}
        path: ./SpringSalad_${{ github.event.inputs.tag_name }}.jar
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TEST }}
      with:
        tag_name: ${{ github.event.inputs.tag_name }}
        release_name: Release ${{ github.event.inputs.tag_name }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TEST }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./SpringSalad_${{ github.event.inputs.tag_name }}.jar
        asset_name: SpringSalad_${{ github.event.inputs.tag_name }}.jar
        asset_content_type: application/java-archive
      
    
  
    

      
